theme = "onedark"

[editor]
line-number = "relative"
mouse = false

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { j = "normal_mode" } # Maps `jj` to exit insert mode
